FROM node:lts-alpine3.20 AS base
# ------------------------------------------------ base
WORKDIR /app

ARG USERNAME=angular

RUN apk update \
    && apk upgrade \
    && adduser -s /bin/sh -D ${USERNAME} \
    && chown -R ${USERNAME}:${USERNAME} /app

FROM base AS builder
# ------------------------------------------------ base
COPY . /app/

RUN npm install --omit=dev \
    && npx ng build

FROM nginx:1.27-alpine AS production
# ------------------------------------------------ builder
WORKDIR /etc/nginx/ssl

ARG APP_NAME

COPY docker/nginx/ssl/ /etc/nginx/ssl/
COPY docker/nginx/conf.d/default.conf.template /etc/nginx/templates/
COPY --from=builder /app/dist/${APP_NAME}/ /app


FROM base AS development
# ------------------------------------------------ development
ARG USERNAME=angular
ARG APP_NAME
ARG APP_DOMAIN

WORKDIR /etc/nginx/ssl

RUN apk update \
    && apk add --update --no-cache \
        npm \
        git \
        openssh \
        nss \
        curl \
    && npm install -g @angular/cli \
    && curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64" \
    && chmod +x mkcert-v*-linux-amd64 \
    && cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert \
    && mkcert \
        -key-file certificate.key \
        -cert-file certificate.pem \
        ${APP_DOMAIN} \
    && chown -R ${USERNAME}:${USERNAME} \
        certificate.key \
        certificate.pem

WORKDIR /app

ENV PATH=/home/${USERNAME}/tools:${PATH}

COPY --chown=${USERNAME}:${USERNAME} docker/tools/ /home/${USERNAME}/tools

USER ${USERNAME}
